export default {
  constants: {
    NOT_FOUND: 'NOT_FOUND',
    WRONG_USER_TYPE: 'WRONG_USER_TYPE',
    NO_SUCH_USER: 'NO_SUCH_USER',
    NO_SUCH_TOKEN: 'NO_SUCH_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
    NOT_ENOUGH_PARAMETERS: 'NOT_ENOUGH_PARAMETERS',
    AUTH_ERROR: 'AUTH_ERROR',
    INVALID_EMAIL: 'INVALID_EMAIL',
    TOO_MANY_CHARACTERS: 'TOO_MANY_CHARACTERS',
    TOO_FEW_CHARACTERS: 'TOO_FEW_CHARACTERS',
    REQUIRED: 'REQUIRED',
    INVALID_PHONENR: 'INVALID_PHONENR',
    TRANSLATION_ERROR: 'TRANSLATION_ERROR',
    UPLOAD_ERROR: 'UPLOAD_ERROR',
    FILE_TOO_BIG: 'FILE_TOO_BIG',
    ALREADY_EXISTS: 'ALREADY_EXISTS'
  }
};
